# Generated by Django 4.1.4 on 2023-02-14 16:21

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_colors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycolor',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitycolor',
            name='color_hex',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='kolor'),
        ),
    ]
