# Generated by Django 4.1.4 on 2022-12-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_alter_activity_description_alter_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagram.subdivision'),
        ),
    ]
