# Generated by Django 4.1.4 on 2022-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0004_activity_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='driving_license',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='kat. prawa jazdy'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='imię ojca'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='nr leg. służb.'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='personal_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PESEL'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='stanowisko'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(verbose_name='data zakończenia'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(choices=[('', ''), ('SŁ.OF', 'służba oficera'), ('SŁ.POM', 'służba pomocnika'), ('SŁ.PDF', 'służba podoficera'), ('SŁ.DYŻ', 'służba dyżurnego'), ('SŁ.PST', 'służba PST'), ('SŁ.PKT', 'służba PKT'), ('PA GAR', 'służba PA garnizonu'), ('PA JW', 'służba PA JW'), ('PO SŁ.', 'po służbie'), ('DYŻUR', 'dyżur'), ('UR.WYP', 'urlop wypoczynkowy'), ('UR.DOD', 'urlop dodatkowy'), ('UR.OK', 'urlop okolicznościowy'), ('UR.OJC', 'urlop ojcowski'), ('UR.WYC', 'urlop wychowawczy'), ('UR.SZK', 'urlop szkoleniowy'), ('WOLNE', 'wolne'), ('POLIG', 'poligon'), ('KURS', 'kurs'), ('L4', 'zwolnienie lekarskie'), ('INNE', 'inne'), ('HDK', 'HDK')], max_length=30, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='soldier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagram.soldier', verbose_name='żołnierz'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(verbose_name='data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagram.subdivision', verbose_name='pododdział'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(choices=[('szer.', 'szer.'), ('st. szer.', 'st. szer.'), ('st. szer. spec.', 'st. szer. spec.'), ('kpr.', 'kpr.'), ('st. kpr.', 'st. kpr'), ('plut.', 'plut.'), ('sierż.', 'sierż.'), ('st. sierż.', 'st. sierż.'), ('mł. chor.', 'mł. chor.'), ('chor.', 'chor.'), ('st. chor.', 'st. chor.'), ('st. chor. sztab.', 'st. chor. sztab.'), ('ppor.', 'ppor.'), ('por.', 'por.'), ('kpt.', 'kpt.'), ('mjr', 'mjr'), ('ppłk', 'ppłk'), ('płk', 'płk'), ('gen. bryg.', 'gen. bryg.')], max_length=20, verbose_name='stopień'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagram.subdivision', verbose_name='pododdział'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagram.subdivision', verbose_name='pododdział'),
        ),
    ]
