# Generated by Django 4.1.4 on 2022-12-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0005_soldier_driving_license_soldier_father_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='id_card_number',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='personal_number',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='position',
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(choices=[('', ''), ('SŁ.OF', 'służba oficera'), ('SŁ.POM', 'służba pomocnika'), ('SŁ.PDF', 'służba podoficera'), ('SŁ.DYŻ', 'służba dyżurnego'), ('SŁ.PST', 'służba PST'), ('SŁ.PKT', 'służba PKT'), ('PA GAR', 'służba PA garnizonu'), ('PA JW', 'służba PA JW'), ('PO SŁ.', 'po służbie'), ('DYŻUR', 'dyżur'), ('OKO', 'OKO'), ('UR.WYP', 'urlop wypoczynkowy'), ('UR.DOD', 'urlop dodatkowy'), ('UR.OK', 'urlop okolicznościowy'), ('UR.OJC', 'urlop ojcowski'), ('UR.WYC', 'urlop wychowawczy'), ('UR.SZK', 'urlop szkoleniowy'), ('WOLNE', 'wolne'), ('POLIG', 'poligon'), ('KURS', 'kurs'), ('L4', 'zwolnienie lekarskie'), ('INNE', 'inne'), ('HDK', 'HDK')], max_length=30, verbose_name='nazwa'),
        ),
        migrations.CreateModel(
            name='SoldierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(default='', max_length=30)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagram.soldier', verbose_name='żołnierz')),
            ],
        ),
    ]
