# Generated by Django 4.1.4 on 2023-01-26 11:51

import diagram.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0007_alter_activity_end_date_alter_soldierinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydayactivity',
            name='how_many',
            field=models.IntegerField(default=1, validators=[diagram.functions.validate_how_many_everyday_activities], verbose_name='ile dziennie'),
        ),
        migrations.CreateModel(
            name='ActivityColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(choices=[('', ''), ('SŁ.OF', 'służba oficera'), ('SŁ.POM', 'służba pomocnika'), ('SŁ.PDF', 'służba podoficera'), ('SŁ.DYŻ', 'służba dyżurnego'), ('SŁ.PST', 'służba PST'), ('SŁ.PKT', 'służba PKT'), ('PA GAR', 'służba PA garnizonu'), ('PA JW', 'służba PA JW'), ('PO SŁ.', 'po służbie'), ('DYŻUR', 'dyżur'), ('OKO', 'OKO'), ('UR.WYP', 'urlop wypoczynkowy'), ('UR.DOD', 'urlop dodatkowy'), ('UR.OK', 'urlop okolicznościowy'), ('UR.OJC', 'urlop ojcowski'), ('UR.WYC', 'urlop wychowawczy'), ('UR.SZK', 'urlop szkoleniowy'), ('WOLNE', 'wolne'), ('POLIG', 'poligon'), ('KURS', 'kurs'), ('L4', 'zwolnienie lekarskie'), ('INNE', 'inne'), ('HDK', 'HDK')], max_length=20, verbose_name='aktywność')),
                ('color_hex', models.CharField(max_length=7, verbose_name='kolor')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagram.subdivision', verbose_name='pododdział')),
            ],
        ),
    ]
