# Generated by Django 4.1.4 on 2023-01-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0008_alter_everydayactivity_how_many_activitycolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydayactivity',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nazwa'),
        ),
        migrations.DeleteModel(
            name='ActivityColor',
        ),
    ]
