# Generated by Django 4.1.4 on 2023-02-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0010_activity_demo_everydayactivity_demo_soldier_demo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nazwa'),
        ),
    ]
