# Generated by Django 4.1.4 on 2023-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0012_alter_subdivision_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='nazwa'),
        ),
    ]
