RANKS = (
    ('szer.', 'szer.'),
    ('st. szer.', 'st. szer.'),
    ('st. szer. spec.', 'st. szer. spec.'),
    ('kpr.', 'kpr.'),
    ('st. kpr.', 'st. kpr'),
    ('plut.', 'plut.'),
    ('sierż.', 'sierż.'),
    ('st. sierż.', 'st. sierż.'),
    ('mł. chor.', 'mł. chor.'),
    ('chor.', 'chor.'),
    ('st. chor.', 'st. chor.'),
    ('st. chor. sztab.', 'st. chor. sztab.'),
    ('ppor.', 'ppor.'),
    ('por.', 'por.'),
    ('kpt.', 'kpt.'),
    ('mjr', 'mjr'),
    ('ppłk', 'ppłk'),
    ('płk', 'płk'),
    ('gen. bryg.', 'gen. bryg.'),
)

ACTIVITY_NAMES = (
    ('', ''),
    ('SŁ.OF', 'służba oficera'),
    ('SŁ.POM', 'służba pomocnika'),
    ('SŁ.PDF', 'służba podoficera'),
    ('SŁ.DYŻ', 'służba dyżurnego'),
    ('SŁ.PST', 'służba PST'),
    ('SŁ.PKT', 'służba PKT'),
    ('PA GAR', 'służba PA garnizonu'),
    ('PA JW', 'służba PA JW'),
    ('PO SŁ.', 'po służbie'),
    ('DYŻUR', 'dyżur'),
    ('OKO', 'OKO'),
    ('UR.WYP', 'urlop wypoczynkowy'),
    ('UR.DOD', 'urlop dodatkowy'),
    ('UR.OK', 'urlop okolicznościowy'),
    ('UR.OJC', 'urlop ojcowski'),
    ('UR.WYC', 'urlop wychowawczy'),
    ('UR.SZK', 'urlop szkoleniowy'),
    ('WOLNE', 'wolne'),
    ('POLIG', 'poligon'),
    ('KURS', 'kurs'),
    ('L4', 'zwolnienie lekarskie'),
    ('INNE', 'inne'),
    ('HDK', 'HDK'),
)

DEFAULT_SOLDIER_INFO = [
    'stanowisko',
    'PESEL',
    'imię ojca',
    'nr leg. sł.',
    'kat. prawa jazdy',
]

SOLDIER_INFO_NAME_CHANGE_PREFIX = 'Dotychczasowa nazwa: '
