ranks = (
    ('szer.', 'szer.'),
    ('st. szer.', 'st. szer.'),
    ('st. szer. spec.', 'st. szer. spec.'),
    ('kpr.', 'kpr.'),
    ('st. kpr.', 'st. kpr'),
    ('plut.', 'plut.'),
    ('sierż.', 'sierż.'),
    ('st. sierż.', 'st. sierż.'),
    ('mł. chor.', 'mł. chor.'),
    ('chor.', 'chor.'),
    ('st. chor.', 'st. chor.'),
    ('st. chor. sztab.', 'st. chor. sztab.'),
    ('ppor.', 'ppor.'),
    ('por.', 'por.'),
    ('kpt.', 'kpt.'),
    ('mjr', 'mjr'),
    ('ppłk', 'ppłk'),
    ('płk', 'płk'),
    ('gen. bryg.', 'gen. bryg.'),
)

activity_names = (
    ('służba oficera', 'służba oficera'),
    ('służba pomocnika', 'służba pomocnika'),
    ('służba podoficera', 'służba podoficera'),
    ('służba dyżurnego', 'służba dyżurnego'),
    ('służba PST', 'służba PST'),
    ('służba PKT', 'służba PKT'),
    ('służba PA garnizonu', 'służba PA garnizonu'),
    ('służba PA JW', 'służba PA JW'),
    ('dyżur', 'dyżur'),
    ('urlop', 'urlop'),
    ('wolne', 'wolne'),
    ('poligon', 'poligon'),
    ('kurs', 'kurs'),
    ('zwolnienie lekarskie', 'zwolnienie lekarskie'),
    ('inne', 'inne'),
)
